#!/bin/sh
launchctl unload /System/Library/LaunchDaemons/com.apple.appstored.plist
launchctl unload /System/Library/LaunchDaemons/com.apple.itunesstored.plist
launchctl load /System/Library/LaunchDaemons/com.apple.appstored.plist
launchctl load /System/Library/LaunchDaemons/com.apple.itunesstored.plist
exit 0