include theos/makefiles/common.mk

BUNDLE_NAME = AppstoreUnrestrictSettings
AppstoreUnrestrictSettings_FILES = /mnt/d/codes/appstoreunrestrict/appstoreunrestrictsettings/AppstoreUnrestrictSettingsController.mm
AppstoreUnrestrictSettings_INSTALL_PATH = /Library/PreferenceBundles
AppstoreUnrestrictSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
AppstoreUnrestrictSettings_PRIVATE_FRAMEWORKS = Preferences
AppstoreUnrestrictSettings_CFLAGS = -fobjc-arc
AppstoreUnrestrictSettings_LDFLAGS = -Wl,-segalign,4000
AppstoreUnrestrictSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk
